apiVersion: v1
kind: Namespace
metadata:
  name: bakery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bakery-deployment
  namespace: bakery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bakery
  template:
    metadata:
      labels:
        app: bakery
    spec:
      containers:
        - name: bakery-container
          image: tribelcheif/bakery:latest   # <-- replace with your image
          ports:
            - containerPort: 8080           # <-- target port of your app
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: bakery-service
  namespace: bakery
spec:
  selector:
    app: bakery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080                  # <-- same as containerPort
  type: LoadBalancer                    # Change to ClusterIP if needed
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bakery-hpa
  namespace: bakery
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bakery-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30
